// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLp_dnzP3dp_eUnU5eKOlGixT7y_HBzQo',
    appId: '1:874425646411:android:f87304e1a275ff463c7cce',
    messagingSenderId: '874425646411',
    projectId: 'mynotes-muhab2001',
    storageBucket: 'mynotes-muhab2001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN8YsFhHlRjLJwGHHI6ylW9_TCdEjLyCA',
    appId: '1:874425646411:ios:105acf9b1da748a23c7cce',
    messagingSenderId: '874425646411',
    projectId: 'mynotes-muhab2001',
    storageBucket: 'mynotes-muhab2001.appspot.com',
    iosClientId: '874425646411-fbhv1243nqi5680lt8k7o4n8m5lpnjas.apps.googleusercontent.com',
    iosBundleId: 'com.muhabdummy.mynotes',
  );
}
